services:
  - type: web
    name: spotify-player
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.20.1
      - key: CLIENT_ID
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
